version: "3.9"

services:
  app:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    volumes:
      - .:/app:cached
      - node-modules:/app/node_modules

volumes:
  node-modules:
